name: Launch test
# This workflow is triggered on pushes to the repository.
on: push

jobs:
  checks:
    name: Run test
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
    # https://github.com/cedrickring/golang-action
    - uses: actions/checkout@master

    - name: run
      uses: cedrickring/golang-action@1.4.1